// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwoFKsSameTable.Data;

#nullable disable

namespace TwoFKsSameTable.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220527201158_TwoFKsSameTable")]
    partial class TwoFKsSameTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploDois.PessoaDois", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Funcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PessoasDois");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploDois.ReceitaDois", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoFK")
                        .HasColumnType("int");

                    b.Property<string>("Prescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoFK");

                    b.HasIndex("UtenteFK");

                    b.ToTable("ReceitasDois");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploUm.PessoaUm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Funcao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PessoasUm");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploUm.ReceitaUm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoFK")
                        .HasColumnType("int");

                    b.Property<string>("Prescricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoFK");

                    b.HasIndex("UtenteFK");

                    b.ToTable("ReceitasUm");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploDois.ReceitaDois", b =>
                {
                    b.HasOne("TwoFKsSameTable.Models.ExemploDois.PessoaDois", "Medico")
                        .WithMany("ListaReceitasCriadas")
                        .HasForeignKey("MedicoFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TwoFKsSameTable.Models.ExemploDois.PessoaDois", "Utente")
                        .WithMany("ListaReceitasAtribuidas")
                        .HasForeignKey("UtenteFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploUm.ReceitaUm", b =>
                {
                    b.HasOne("TwoFKsSameTable.Models.ExemploUm.PessoaUm", "Medico")
                        .WithMany("ListaReceitasCriadas")
                        .HasForeignKey("MedicoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwoFKsSameTable.Models.ExemploUm.PessoaUm", "Utente")
                        .WithMany("ListaReceitasAtribuidas")
                        .HasForeignKey("UtenteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploDois.PessoaDois", b =>
                {
                    b.Navigation("ListaReceitasAtribuidas");

                    b.Navigation("ListaReceitasCriadas");
                });

            modelBuilder.Entity("TwoFKsSameTable.Models.ExemploUm.PessoaUm", b =>
                {
                    b.Navigation("ListaReceitasAtribuidas");

                    b.Navigation("ListaReceitasCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
